name: Build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  setup:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-version
      id: get_version
      run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  build-ios-library:
    needs: [setup]
    runs-on: macos-13
    env:
      PACKAGENAME: librwkv_mobile-${{ needs.setup.outputs.VERSION }}-ios-static
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      IOS_DEPLOYMENT_TARGET: '13.0'
      ENABLE_BITCODE: OFF
      ENABLE_ARC: OFF
      ENABLE_VISIBILITY: OFF
    steps:
    - uses: actions/checkout@v4
    - name: build-arm64
      run: |
        mkdir build-arm64 && cd build-arm64
        cmake .. -DENABLE_NCNN_BACKEND=OFF -DENABLE_WEBRWKV_BACKEND=ON -DBUILD_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build . -j 8
    - name: package
      run: |
        rm -f ${{ env.PACKAGENAME }}.zip
        pushd build-arm64
        zip -9 -y -r ../${{ env.PACKAGENAME }}.zip librwkv_mobile.a
        popd
    - name: upload-zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip

  build-android-library:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: librwkv_mobile-${{ needs.setup.outputs.VERSION }}-aarch64-android-ndk-r25c
    steps:
    - uses: actions/checkout@v4
    - name: Install Ninja
      run: |
        sudo apt-get install ninja-build
    - name: ndk-r25c
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O $GITHUB_WORKSPACE/android-ndk-r25c-linux.zip
        cd $GITHUB_WORKSPACE && unzip -q android-ndk-r25c-linux.zip
    - name: build
      run: |
        mkdir build && cd build
        cmake .. -DENABLE_NCNN_BACKEND=ON -DENABLE_WEBRWKV_BACKEND=OFF \
          -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-28 -DANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r25c \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/android-ndk-r25c/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -G Ninja
        ninja
    - name: package
      run: |
        rm -f ${{ env.PACKAGENAME }}.zip
        pushd build-arm64
        zip -9 -y -r ../${{ env.PACKAGENAME }}.zip librwkv_mobile.so
        popd
    - name: upload-zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip
  
  upload-dev-release:
    needs: [setup, build-ios-library, build-android-library]
    runs-on: ubuntu-latest
    steps:
      - name: download-ios
        uses: actions/download-artifact@v4
        with:
          name: librwkv_mobile-${{ needs.setup.outputs.VERSION }}-ios-static

      - name: download-android
        uses: actions/download-artifact@v4
        with:
          name: librwkv_mobile-${{ needs.setup.outputs.VERSION }}-aarch64-android-ndk-r25c

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            librwkv_mobile-${{ needs.setup.outputs.VERSION }}-ios-static.zip
            librwkv_mobile-${{ needs.setup.outputs.VERSION }}-aarch64-android-ndk-r25c.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            librwkv_mobile-${{ needs.setup.outputs.VERSION }}-ios-static.zip
            librwkv_mobile-${{ needs.setup.outputs.VERSION }}-aarch64-android-ndk-r25c.zip