name: Build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  setup:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-version
      id: get_version
      run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

  build-ios:
    needs: [setup]
    runs-on: macos-13
    env:
      PACKAGENAME: librwkv_mobile-${{ needs.setup.outputs.VERSION }}-ios-static
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      IOS_DEPLOYMENT_TARGET: '13.0'
      ENABLE_BITCODE: OFF
      ENABLE_ARC: OFF
      ENABLE_VISIBILITY: OFF
    steps:
    - uses: actions/checkout@v4
    - name: build-arm64
      run: |
        mkdir build-arm64 && cd build-arm64
        cmake .. -DENABLE_NCNN_BACKEND=OFF -DENABLE_WEBRWKV_BACKEND=ON -DBUILD_STATIC_LIB=ON
        cmake --build . -j 8
        cmake --build . --config Release
